version: '3.7'
services:
  users-mysql:
    image: users-mysql
    ports:
      - 8086:8080
    depends_on:
      - mysql_test
    networks:
      movie-quote-network:
        aliases:
          - spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_test:3306/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
  mysql_test:
    image: mysql:5.6
    networks:
      movie-quote-network:
        aliases:
          - mysql_test
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ONETIME_PASSWORD=true
networks:
  movie-quote-network:
