spring:
  datasource:
    url: jdbc:mysql://mysql_test:3306/test
    username: sa
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: create
      # Naming strategy
      naming-strategy: org.hibernate.dialect.MySQLDialect

server:
  port: 8086